language: node_js
node_js:
  - "15"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - yarn install
  - yarn generate
script:
  - echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_ACCESS_TOKEN"
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      - nessunoescluso:kGIR9oCAutxpT7YTygEJeqKN#engineering
    on_success: always
    on_start: always
