language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - yarn install
  - yarn generate
  - cp logs.log dist
script:
  - echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_ACCESS_TOKEN"
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      - nessunoescluso:kGIR9oCAutxpT7YTygEJeqKN#engineering
    on_success: always
    on_failure: always
    on_start: always
env:
  global:
    - secure: l/oFv6WiPg+fiEE+98r8YnYd1B0ZSIJxiEEPHihTJDB7eicKYnT+VHRR8HSYbvn2Xl6yRz36pZuK/KGyiHser7q0/bNkbsUA7igpKPvfED2RFCGqC31lldyEo/ZNJeGciwzFkEGp6HPG876N32kE2D/tXDXCI7XGp9pEl0uP9jKvcjHXVsnXHzIbOU7ecrZFeB0Ng7Ck9HWVBVsUqFNnGhHnDoueNDuTCHolcLrRBtACacLoCnrMf+DbHPo0ew5oOxcuUXHi5n6yUSKlshdgM7bZWwUKLmnAkgzCrbAP6lgyFPcK+146uu3+bmdJMPYd4jzEFBHxJ/dHOyV5CG+ACuD/3pfGJW/G579Tz0d9P8b2WvKY2XlbcJBLA/kj4+7P4IvlHZWOJdJw6KsUnPZfbvWJB6ZAc79cn5Ag1V49VJJzCtG+k1gN7kb9t7KkFwGWbSz/x36HxSB/ssFakOJ+SKIl8WFaljWuFviB9oxEU8V80l6EarhAd8Ww0/8OYVvSaWmwS8U72NPm/DlWEVgfwGHJUjck7K/rii1jyh/pWuCu84l4yu2vQwl8RVl9RNJLOMltRFsxF59fumGLfBU7OjXuyZAcobeHMsnGVrun/SoSXGl7OGTknV1uyGeHZj565xqVnvVTPmEwCRjMLfFJZ9AplWLlhZKErwVVIWc5M4U=
    - secure: BCBaemXY57TiL1iJrCEcIJ4Mkvn56grzR5s7IJzGPSGs/oK/2UnS7DYqkzomDtAPGVghNf4fabL90rn4OnHr0FJ+rCXtxDGloUrD2wtnJ2XHiJcY4qKqLHCDB5uIOIjfOSxZsj86qldp1cfrtQdw3dVxHmxRF4qRYo5WNgIdY9WVitOb/bSOgRnMW9tLpvtVC9rkme9S5p4LpLgKwaGThI3vZcj9P64kaWUmksD+YfMqPx3bLhj0WjrBnAJcHbcjKBX86CIOkqt/xB/UIClscXVQ1Ch6BHhrpZoaKekqrNlHVMXMBmkk6m5tuWVa2nJrnNRNk8ICv5qbHABsSsVt7mvezQksRSNTgekAFyXNhMbugzPZNxBVYJC/vYoduWwn/jvFKsEqNrnEHhPVJM8YQDqabRo/Os/aJko+C7FSRlC650D9u8Sdy881wb8lY3uowgVfPmphDNggL96SxEu66JNB/RvcVxCCHFdUgsHs3I1uR1jf3ha8iqIC1HANl9TEEcIs3+MW/EN+F7LGW8Vo1un0Nj+uTn1+chhrVeSmaorivAClfG1EFyCQQ9zD3KVpBNnyJrHJNqG+4L1QSCKPfsSIc0hr4A3UDiwiggyrmgF+gX2rukOo1HQ0L7N7260XcVdi4Keq3h2twbkkZPXN7ZG2qhUXpv+RDpzkwuWhiUc=
