{
  repository(owner: "sangiovannilipioni", name: "sangiovannilipioni.api") {
    defaultBranchRef {
      target {
        ... on Commit {
          history(first: 1) {
            nodes {
              oid
            }
          }
        }
      }
    }
  }
}
